### PR TITLE
Remove error chain (new)

### PR DESCRIPTION
**Pull request by sebest**
All the context in is PR #44

### CODE REVIEW

**Comment by sebest** [comment]
Can we tag a new release if everything looks good?

**Review by zslayton — APPROVED** [review]
Thanks!

**Comment by sebest** [comment]
Is there anything to do to merge the PR?

**Comment by zslayton** [comment]
There's at least one other PR I'd like to try and land before I cut a new release but I plan to do it this week.

Thanks for contributing!

**Comment by zslayton** [comment]
@sebest: I just cut [a `v0.8.0` release](https://github.com/zslayton/cron/releases/tag/v0.8.0) that includes this along with a number of substantial pieces of functionality.

**Pull request merged**
