### PR TITLE
add `into_upcoming` to `Schedule`

### PR DESCRIPTION
**Pull request by nooberfsh**

### CODE REVIEW

**Comment by zslayton** [comment]
Hi, thanks for the PR. Can you give me an example of functionality that this will enable?

**Comment by nooberfsh** [comment]
It is like `iter()` and `into_iter()`. 
Sometimes I need pass the return type across thread boundary which need `'static` lifetime, e.g. `tokio::spawn`, `std::thread::spawn`

**Comment by nooberfsh** [comment]
@zslayton Can we merge this?

**Comment by zslayton** [comment]
I'm not against adding this functionality, but I'd like to better understand why the extra API surface area is necessary.

> Sometimes I need pass the return type across thread boundary which need 'static lifetime, e.g. `tokio::spawn`, `std::thread::spawn`

Why is passing a consuming iterator across the thread boundary better than passing the `Schedule` itself and then creating an iterator? Can you give me a mock example of your use case?

**Comment by zslayton** [comment]
Revisiting this as part of a cleanup. What are your thoughts on passing the `Schedule` over the thread boundary instead?

**Comment by nooberfsh** [comment]
Sorry for late the reply.

>Why is passing a consuming iterator across the thread boundary better than passing the Schedule itself and then creating an 
iterator? 

You are right,  passing the `Schedule` can solve the problem.

**Pull request closed without merging**
