### PR TITLE
Added partialeq and eq derives

### LINKED ISSUE #61: PartialEq and Eq for the Schedule type
Hi! I am working on something and it would be nice to be able to do comparisons with the Schedule types.

### PR DESCRIPTION
**Pull request by celaus**
Fixes #61

### CODE REVIEW

**Comment by zslayton** [comment]
Hi, thanks for the PR.

Using a `derive` implementation of `Eq`/`PartialEq` means that two `Schedule`s will only be equal if:
1. They represent the same set of datetimes
   AND
2. The [source strings that were parsed](https://github.com/zslayton/cron/pull/62/files#diff-dce650093f94ff40ea28c13f363195e6968eeb17883f90a4d3cac98958fbe453L15) to create the two `Schedule`s are identical.

This might be a narrower definition of equality than we want, since you could have a schedule with a day field of `SUN,MON,TUES,WED,THU,FRI,SAT` and one with `*` and they'd represent the same conceptual schedule.

Any thoughts on this?

**Comment by celaus** [comment]
Hmm true, that might be a too narrow definition. 

I'd say if two instances represent the same datetimes and one has a source string and the other doesn't, they should still be equal. However I don't know cron syntax well enough to know if there is an example for the other way around as well, i.e. when the source strings are different but result in the same datetime representations... 

I'm happy to implement whatever definition we agree on 😄

**Comment by zslayton** [comment]
> Otherwise I'd say we compare source strings when available and datetime (only) for the rest?

The source string will always be available. (The source string is an `Option` in the struct [as a bit of a workaround](https://github.com/zslayton/cron/pull/54#issue-455758124)).

I'm inclined to say let's implement it using source string equality for now. Determining the equality of the cron schedule the string represents is much trickier, especially if the parser adds support for other syntaxes in the future.

Out of interest, what's your main use case for `PartialEq` and `Eq`?

**Comment by celaus** [comment]
I wanted to keep actions that run on the same schedule as a `HashMap<Schedule, Vec<ExecuteOnSchedule>` 😄  
(I haven't worked on that particular project for a while)

**Comment by zslayton** [comment]
`PartialEq` and `Eq` implementations were added in PR #78.

**Comment by celaus** [comment]
Thank you everyone for pitching in!

**Pull request closed without merging**
