### PR TITLE
add '?' support in DOM, DOW fields 

### PR DESCRIPTION
**Pull request by elbe0046**
Support for '?' in DOM and DOW fields was necessary for my use case, and I noticed that https://github.com/zslayton/cron/issues/47 already existed, so I'm curious if there'd be interest in landing something in roughly this form?

### CODE REVIEW

**Comment by zslayton** [comment]
Hey, thanks for the PR! Apologies for the delayed review.

I want to check my understanding here. It looks like `?` behaves identically to `*` except that it is restricted to two fields (day of week and day of month) and can only be used in up to one of those fields in a single expression. Is that right?

**Comment by elbe0046** [comment]
> I want to check my understanding here. It looks like `?` behaves identically to `*` except that it is restricted to two fields (day of week and day of month) and can only be used in up to one of those fields in a single expression. Is that right?

Yes, that is correct for both parts.  Restricting `?` to only be used in at most one of the two applicable fields was done to follow suit from implementations like quartz scheduler, but that restriction could be lifted here that is the preferred approach.

**Comment by zslayton** [comment]
> Restricting ? to only be used in at most one of the two applicable fields was done to follow suit from implementations like quartz scheduler, but that restriction could be lifted here that is the preferred approach.

That was my thinking as well; I think treating `?` as a synonym for `*` would allow `cron` to accept all of the patterns people would want to parse while simplifying the code change quite a bit. (We wouldn't need to split `Field` into `DayOf` and `Standard`, for instance.)

I think you'd keep [this change to longhand](https://github.com/zslayton/cron/pull/57/files#diff-f5a6aa49bd9b68c1b8dda9efc27c4475R684) where you've broken the fields out, and we'd need a simple "`?` or `field`" parser that could be called for the `days_of_month` and `days_of_week` fields. (I'm not able to validate this at the moment, I'm just going from a skim of the PR diff.) How's that sound to you?

**Comment by elbe0046** [comment]
> That was my thinking as well; I think treating `?` as a synonym for `*` would allow `cron` to accept all of the patterns people would want to parse while simplifying the code change quite a bit. (We wouldn't need to split `Field` into `DayOf` and `Standard`, for instance.)
> 
> I think you'd keep [this change to longhand](https://github.com/zslayton/cron/pull/57/files#diff-f5a6aa49bd9b68c1b8dda9efc27c4475R684) where you've broken the fields out, and we'd need a simple "`?` or `field`" parser that could be called for the `days_of_month` and `days_of_week` fields. (I'm not able to validate this at the moment, I'm just going from a skim of the PR diff.) How's that sound to you?

Yeah all of this sounds good to me.

> I think treating `?` as a synonym for `*` would allow `cron` to accept all of the patterns people would want to parse while simplifying the code change quite a bit. (We wouldn't need to split `Field` into `DayOf` and `Standard`, for instance.)

Just to confirm, you're suggesting that `?` and `*` be interchangeable only for DOM and DOW fields, correct?  The latter portion of your comment seemed to indicate this, but checking in case you were meaning to make them synonymous for all fields.

**Comment by zslayton** [comment]
> Just to confirm, you're suggesting that ? and * be interchangeable only for DOM and DOW fields, correct?

Right. I think that gets us pretty close to the actual `?` use case for a relatively low complexity cost.

**Comment by zslayton** [comment]
Hi, are you still interested in implementing this?

**Comment by elbe0046** [comment]
> Hi, are you still interested in implementing this?

Ah yes I'm sorry this got a bit lost in the shuffle.  I hope to have something up today or tomorrow.

**Comment by elbe0046** [comment]
Thanks for your patience.  When you get a chance, let me know if these updates align with what you had envisioned.

**Comment by zslayton** [comment]
This looks excellent, thank you for putting it together!

**Pull request merged**
