### PR TITLE
Add Debug trait to Schedule

### PR DESCRIPTION
**Pull request by rtyler**
I have found this helpful when including `cron::Schedule` in other structs

### CODE REVIEW

**Comment by rtyler** [comment]
Oh bollocks, looks like I need to extend the `Debug` chain a bit further!

That's what I get for making a quick inline edit on GitHub dot com

**Comment by zslayton** [comment]
Yeah, I just saw the failing CI build. I'll check in on it later and merge when it's passing.

**Comment by rtyler** [comment]
@zslayton if I find some time and motivation, I might work a serde deserializer feature in here too, but for now I'm using [this approach](https://brokenco.de/2020/08/03/serde-deserialize-with-string.html)

**Comment by zslayton** [comment]
Passing now, thanks for the PR! 

I'd be happy to review another for a serde feature if that's straightforward to implement. If it would require substantial design/code, please open an issue first so we can sketch out what that would look like before you get too far along.

**Pull request merged**
