### PR TITLE
fixed step_by change rust issue #27741

### PR DESCRIPTION
**Pull request by william20111**
Ignoring the rustfmt stuff, its just adding the step by feature as its changed. And it takes usize now so added a cast to that.

Rust - https://github.com/rust-lang/rust/issues/27741

```rust
#![feature(iterator_step_by)]
```

### CODE REVIEW

**Comment by mehcode** [comment]
I'd say we should just change the [underlying types](https://github.com/zslayton/cron/blob/master/src/schedule.rs#L227) to `usize` rather than have the cast.

**Comment by william20111** [comment]
Makes much more sense. Still getting to know the crate so might be better suited to somebody more comfortable with the code.

**Comment by zslayton** [comment]
@william20111 Thanks! 

@mehcode It is my understanding that `usize` should be reserved for data that is dependent on the architecture (i.e. pointers/indexes). Some guidelines are discussed [here](https://github.com/rust-lang/rust/issues/22240). All of the values being represented in this crate have a very limited domain: 0-59 seconds/minutes, 0-23 hours, 0-31 days of the month, etc. I could safely represent them each as a single `u8`. In fact, I probably should since I'm storing several trees with dozens of values each and that would be a nice space savings.

I'm going to merge this PR. Please open an issue if you'd like to discuss it further.

**Comment by mehcode** [comment]
@zslayton Makes sense.

**Pull request merged**
